gpu support
carsdotcom/skelebot pull request #203
Opened 2021-12-07 04:29 UTC by sherrywang31

Resolves #193

### Solution
Allow user to specify `gpu: True/False` option in config. Add `set_gpu` function in `RunCommandBuilder` and call it in to add gpu related options in runCMD if `gpu` is set to `True` in the config file.

2021-12-07 14:21 UTC, jagmoreira requested changes

2021-12-07 14:21 UTC, jagmoreira commented on CHANGELOG.md
> +## v1.24.1
This feels more like a minor rather than a patch update

2021-12-07 14:21 UTC, jagmoreira commented on CHANGELOG.md
> +#### Merged: 2021-11-17
This version was also released to PYPI.

2021-12-08 15:29 UTC, swangcars commented on CHANGELOG.md
> +#### Merged: 2021-11-17
Added release date

2021-12-08 15:54 UTC, jagmoreira approved these changes

2021-12-08 21:43 UTC, merged